[package]
name = "toDo_List_Journal"
version = "0.1.0"
edition = "2021"

[dependencies]

home = "0.5"
structopt = "0.3"
serde-chrono-str = "0.1"
serde_json = "1.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"
